### ISSUE TITLE
Guide about using Docker

### ISSUE THREAD

**Issue by sh7dm** [imthenachoman/How-To-Secure-A-Linux-Server#31]
Using Docker can help you secure apps and server

**Comment by imthenachoman** [comment]
How? Docker sits on top of the OS. You need to secure the OS first.

**Comment by ShiromMakkad** [comment]
It would be nice to know about any security risks about using Docker. Is something like Fail2Ban as effective when your services containerized? Is it able to read logs inside the containers? I don't know.

**Comment by imthenachoman** [comment]
I have only just started using Docker which is why this guide doesn't speak to it. I will update it once I know more.

But Fail2Ban can only monitor for what you tell it. You can, in theory, configure Fail2Ban to read logs inside the containers and ban appropriately.

**Comment by elesiuta** [comment]
Somewhat related, I recently put together some notes for myself for using LXD, if there's interest I can clean them up a bit more and make a pull request.

My reason for using LXD came down to:
- Don't need the scaling capabilities of Docker
- Not all programs have trusted and well maintained Docker images available, and maintaining a pipeline to build your own is overkill for a personal home server
- LXD creates containers that are unprivileged by default and confined with [apparmor,](https://ubuntu.com/server/docs/containers-lxd) so it is relatively easy to do securely and only a few extra steps on top of installing packages normally
- You can setup [Docker inside of LXD for added security](https://unix.stackexchange.com/questions/254956/what-is-the-difference-between-docker-lxd-and-lxc)

My notes:
### Main references
- https://linuxcontainers.org/lxd/getting-started-cli/
- https://wiki.archlinux.org/index.php/LXD
- https://www.digitalocean.com/community/tutorials/how-to-set-up-and-use-lxd-on-ubuntu-16-04

### setup
sudo snap install lxd
lxd init
accept defaults to everything (don't need ip6 though, can disable later with lxc network set lxdbr0 ipv6.address none)

### create container
lxc launch ubuntu:20.04 \<container name\>

### disable autostart
lxc config set \<container name\> boot.autostart false

### list containers (note container ip, interface is the internal name inside container)
lxc list

### run commands in container or enter interactive shell
lxc exec \<container name\> -- [command to run in container]
lxc exec \<container name\> -- sudo --login --user ubuntu
lxc exec \<container name\> bash

### forward traffic
\<server local interface\> := probably enp34s0, check with 'ip link show' on host
\<server local ip\> := self explanatory
\<port\> := port you want to forward from host to container
\<container ip:port\> := get ip from lxc list, port that is listening inside container
sudo iptables -t nat -I PREROUTING -i \<server local interface\> -p TCP -d \<server local ip\> --dport \<port\> -j DNAT --to-destination \<container ip:port\> -m comment --comment "forward to container"

### list iptables rules
sudo iptables -t nat -L PREROUTING

### make rules persist across reboots
sudo apt install iptables-persistent
sudo netfilter-persistent save

### devices and mounts
https://www.cyberciti.biz/faq/how-to-add-or-mount-directory-in-lxd-linux-container/
https://askubuntu.com/questions/610513/how-do-i-share-a-directory-between-an-lxc-container-and-the-host
https://github.com/lxc/lxd#can-i-bind-mount-my-home-directory-in-a-container
https://github.com/lxc/lxd/blob/master/doc/userns-idmap.md
#### check devices
lxc config device show \<container name\>
#### mount (read only by default)
lxc config device add \<container name\> \<device name\> disk source=\<path on host\> path=\<path on container\>
#### mount (add write permission)
use command 'id' to check uid and gid on host and container (all probably 1000)
lxc config set \<container name\> raw.idmap "both 1000 1000"
#### remove mount
lxc config device remove \<container name\> \<device name\>

### restart container
lxc restart \<container name\>

### ways to check containers (and make sure they are unprivileged)
lxc config show --expanded \<container name\> | grep privileged
ps -ef | grep \<process in container\> # make sure not running as root
lxc config get \<container name\> security.privileged # If that shows "true", then the container is privileged, otherwise it is not
lxc list security.privileged=true # check all at once

**Comment by elesiuta** [comment]
I came across a few services probably worth mentioning that offer an easy to setup and secure method of remotely accessing services in your docker containers as an alternative to a VPN or SSH tunnel.

https://github.com/authelia/authelia
https://github.com/keycloak/keycloak
https://github.com/pomerium/pomerium

**Comment by imthenachoman** [comment]
This is great. Thanks! I think it probably makes sense for Docker to have its own write-up that is independent of the base OS.
